version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/Eureka
    environment:
      ARTPATH: /tmp/artifacts
      TOOLCHAIN: gcc
      FORCECORES: 64
      FORCEANDROID: 1
      FORCEDEVICE: 3

    steps:
      - checkout

      - run: |
          # APT stuff
          apt update &>/dev/null
          apt install git zip build-essential python ccache bc -y &>/dev/null
      - run: |
          # Toolchain download
          rm toolchain
          if [ "$TOOLCHAIN" == gcc ]; then
            BRANCH=GCC-4.9
            ID=gcc4.9
          else
            BRANCH=linaro6.5
            ID=linaro6.5
          fi
          git clone https://github.com/Chatur27/Toolchains-for-Eureka -b "$BRANCH" toolchain &>/dev/null
          touch toolchain/$ID
      - run: |
          mkdir /tmp/artifacts
          for var in 4; do
            FORCESE=$var ./build.sh
          done

      - store_artifacts:
          path: /tmp/artifacts
          destination: files