version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/Eureka
    environment:
      ARTPATH: /tmp/artifacts
      FORCECORES: 64
      FORCEANDROID: 1
      FORCEDEVICE: 3

    steps:
      - checkout

      - run: |
          # APT stuff
          apt update &>/dev/null
          apt install git zip build-essential python ccache bc -y &>/dev/null
      - run: |
          # Linaro stuff
          rm toolchain
          git clone https://github.com/Chatur27/Toolchains-for-Eureka -b linaro6.5 toolchain &>/dev/null
          touch toolchain/linaro6.5
      - run: |
          mkdir /tmp/artifacts
          for var in 1 2 3; do
            FORCESE=$var ./build.sh
          done

      - store_artifacts:
          path: /tmp/artifacts
          destination: files